apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kk2bhkgxu-python 
  janus-idp.io/tekton: kk2bhkgxu-python
  backstage.io/kubernetes-id: kk2bhkgxu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kk2bhkgxu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  